language: ruby
cache: bundler
branches:
  only:
  - gh-pages
  - /.*/
rvm:
  - 2.3.6
  - 2.4.1  
  - 2.5.3
matrix:
  allow_failures:
    - rvm: 2.3.6
    - rvm: 2.4.1
  fast_finish: true
install:
  - travis_retry bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --assume-extension --check-favicon --check-html --allow-hash-href
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
