backend:
  name: github
  repo: vih/historie
  branch: gh-pages # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "list", allow_add: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: false}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - label: Header
        name: header
        widget: object
        fields:
          - {label: Overlay color, name: overlay_color, widget: string}
          - {label: Overlay image, name: overlay_image, widget: string}
          - {label: Caption, name: caption, widget: string}
