name: Build and deploy Jekyll to Github Pages

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
#      - uses: helaili/jekyll-action@2.0.0
#        env:
#          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - uses: ./.github/actions/build-dist-site
        env:
          # Now make sure you add this environment variable.
          # This token will allow us to push to github directly
          # without having to type in our password.
          # The GITHUB_TOKEN is available by default 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
